"""add vps user details

Revision ID: e6c0208380g1
Revises: d5b9197279f0
Create Date: 2026-09-03 03:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c0208380g1'
down_revision: Union[str, Sequence[str], None] = 'd5b9197279f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.String(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'age')
    op.drop_column('users', 'location')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
